name: "release "

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_TAG: ${{ github.sha }}
  BUILD_NAME: electric-cash-build-${{ github.run_id }}

jobs:
  build-binary:
    name: build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build in docker static binaries
        run: docker build -t $BUILD_NAME --build-arg GIT_COMMIT=$GITHUB_REF-$GITHUB_SHA -f ci/docker/Dockerfile.static .

      - name: Copy binaries from docker image
        run: |
          docker create --name elcash $BUILD_NAME
          mkdir elcash-binaries
          docker cp elcash:/code/src/elcashd elcash-binaries/elcashd
          docker cp elcash:/code/src/elcash-cli elcash-binaries/elcash-cli
          docker cp elcash:/code/src/elcash-tx elcash-binaries/elcash-tx
          docker cp elcash:/code/src/elcash-wallet elcash-binaries/elcash-wallet

      - name: Store elcashd and elcash-cli binary
        uses: actions/upload-artifact@v4
        with:
          name: artifact-elcashd
          if-no-files-found: error
          path: |
            elcash-binaries/*

  release:
    name: release on github
    runs-on: ubuntu-latest
    needs:
      - build-binary
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "elcash-binaries/*"
